### ISSUE TITLE
Terminal color doesn't reset back

### ISSUE THREAD

**Issue by arpy8** [fairyfart/TaskEnb-Tool#1]
The font color doesn't seem to change back to the default color once the script terminates. 

![image](https://github.com/fairyfart/TaskEnb-Tool/assets/74809468/6499db3a-ae19-489b-8a77-6a1bc1a0a33c)

**Comment by sssaaapuyoy** [comment]
I apologize for the delay in getting back to you. During that time, I was dealing with some **important** life choices. 
I wanted to let you know that the *issue* has been resolved in the latest version of the program.
https://github.com/DryShower/sssaaapuyoy/releases/tag/v1.2.7

_**If you encounter any further *issues*, please don’t hesitate to let me know.**_ 
Thank you for your understanding and patience!
